[package]
name = "gravity"
version = "0.1.0"
authors = ["Zachary Stewart <zstewart@google.com>"]
edition = "2018"

[features]
debug-timing = []

[dependencies]
bitflags = "1.0"
specs = "0.11"
physics = { path = "../physics" }

[dependencies.xsecurelock-saver]
path = "../"
features = ["engine"]
