[package]
name = "circle-collision"
version = "0.1.0"
authors = ["Zachary Stewart <zstewart@google.com>"]
edition = "2018"

[features]
debug-timing = []

[dependencies]
bitflags = "1.0"
physics = { path = "../physics" }
scene_management = { path = "../scene_management" }
specs = "0.11"
