[package]
name = "xsecurelock-saver"
version = "0.1.0"
authors = ["Zachary Stewart <zstewart@google.com>"]
edition = "2018"

[features]
engine = []
serde-serialize = []

[dependencies]
log = "0.4"
sfml = "0.16"
sigint = { path = "../sigint" }
