[package]
name = "saver_colorstatic"
version = "0.1.0"
authors = ["Zachary Stewart <zstewart@google.com>"]

[dependencies]
rand = "0.5"
sfml = "0.16"
xsecurelock-saver = { path = "../xsecurelock-saver", features = ["simple"] }
