[package]
name = "saver_bevymin"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
xsecurelock-saver = { path = "../xsecurelock-saver", features = ["engine"] }
