[package]
name = "saver_genetic_orbits"
version = "0.1.0"
authors = ["Zachary Stewart <zstewart@google.com>"]

[features]
debug-timing = []

[dependencies]
circle-collision = { path = "../circle-collision" }
dirs = "1.0"
gravity = { path = "../gravity" }
log = "0.4"
nalgebra = "0.15"
num-complex = "0.2"
num-traits = "0.2"
rand = "0.5"
rusqlite = "0.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
sfml = { git = "https://github.com/jeremyletang/rust-sfml.git", branch = "master" }
specs = "0.11"

[dependencies.xsecurelock-saver]
path = "../"
features = ["engine", "serde-serialize"]
